language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev
  - sudo apt-get install -y libevent-dev

install: "pip install -r setup/requirements.txt"

# command to run tests
script: "source autopilot_env.sh && pushd ./test/agent/ && nosetests -s"